"""empty message

Revision ID: 448556c0ed21
Revises: 48e38f90176b
Create Date: 2025-11-02 08:06:38.898706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448556c0ed21'
down_revision = '48e38f90176b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
